"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState, type ReactNode } from "react";
import { Calendar, Close, Grid, LogOut, Menu, Users } from "./icons";

const navigation = [{ href: "/action-plans", label: "Action Plan", icon: Calendar }, { href: "/monitoring", label: "Monitoring", icon: Grid }, { href: "/users", label: "Users", icon: Users }];

export function AppShell({ children }: { children: ReactNode }) {
  const pathname = usePathname(); const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const sidebar = <aside className="flex h-full w-72 flex-col border-r bg-white px-4 py-5"><div className="flex items-center justify-between px-2"><Link className="flex items-center gap-3 font-semibold tracking-tight text-[#173c3a]" href="/action-plans" onClick={() => setMobileMenuOpen(false)}><span className="grid size-9 place-items-center rounded-xl bg-[#173c3a] text-sm font-bold text-[#d7f1ed]">AP</span><span>Action Plan</span></Link><button className="grid size-9 place-items-center rounded-lg text-[#667c7c] lg:hidden" aria-label="Tutup navigasi" onClick={() => setMobileMenuOpen(false)}><Close className="size-5" /></button></div><nav className="mt-10 space-y-1" aria-label="Navigasi utama">{navigation.map(({ href, label, icon: Icon }) => { const active = pathname === href; return <Link key={href} className={`flex h-11 items-center gap-3 rounded-xl px-3 text-sm font-medium transition ${active ? "bg-[#e3f3f0] text-[#116b67]" : "text-[#59706f] hover:bg-[#f1f5f4] hover:text-[#244542]"}`} href={href} onClick={() => setMobileMenuOpen(false)}><Icon className="size-[18px]" />{label}</Link>; })}</nav><div className="mt-auto"><div className="rounded-xl bg-[#f2f6f5] p-3"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-[#c8ebe7] text-xs font-bold text-[#155f5c]">H</span><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#244542]">Hafidh Akbar</p><p className="text-xs text-[#748886]">User aktif</p></div></div></div><Link className="mt-3 flex h-10 items-center gap-3 rounded-xl px-3 text-sm font-medium text-[#667c7c] transition hover:bg-[#f1f5f4] hover:text-[#244542]" href="/login"><LogOut className="size-[18px]" />Keluar</Link></div></aside>;
  return <div className="min-h-screen bg-[#f6f8f8] lg:flex"><div className="hidden lg:fixed lg:inset-y-0 lg:left-0 lg:z-20 lg:block">{sidebar}</div>{mobileMenuOpen && <div className="fixed inset-0 z-50 bg-[#173c3a]/25 lg:hidden"><div className="h-full shadow-[16px_0_48px_-22px_rgba(23,60,58,0.45)]">{sidebar}</div></div>}<div className="flex min-h-screen flex-1 flex-col lg:ml-72"><header className="flex h-16 items-center justify-between border-b bg-white px-4 sm:px-7"><button className="grid size-10 place-items-center rounded-xl border bg-white text-[#32514f] lg:hidden" aria-label="Buka navigasi" onClick={() => setMobileMenuOpen(true)}><Menu className="size-5" /></button><p className="hidden text-sm text-[#6c807f] sm:block">Workspace · September 2026</p><div className="ml-auto flex items-center gap-3"><span className="hidden text-sm font-medium text-[#3a5856] sm:inline">Hafidh Akbar</span><span className="grid size-9 place-items-center rounded-full bg-[#c8ebe7] text-xs font-bold text-[#155f5c]">H</span></div></header><main className="flex-1 px-4 py-7 sm:px-7 lg:px-7 lg:py-7 xl:px-8">{children}</main></div></div>;
}
